### PR TITLE
Verify the /tmp directory is writeable at startup.

### LINKED ISSUE #1263: A race condition leads to the /tmp directory not being usable
apt-get update produces the following:

Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/security.debian.org_dists_jessie_updates_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/ftp.us.debian.org_debian_dists_testing_InReleaseCouldn't create tempfiles for splitting up /var/lib/apt/lists/partial/deb.debian.org_debian_dists_jessie-updates_InReleaseW: GPG error: http://security.debian.org jessie/updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://ftp.us.debian.org testing InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
W: GPG error: http://deb.debian.org jessie-updates InRelease: Could not execute 'gpgv' to verify signature (is gpgv installed?)
E: Couldn't create temporary file to work with /var/lib/apt/lists/deb.debian.org_debian_dists_jessie_Release - mkstemp (2: No such file or directory)

### PR DESCRIPTION
**Pull request by ojarjur**
This fixes #1263

### CODE REVIEW

File: containers/datalab/content/run.sh [hunk 1]
```diff
@@ -115,6 +116,17 @@ watch_and_restart_tunnel() {
   setup_tunnel "${project_id}" "${zone}" "${instance}" "${ssh_user}"
 }
 
+check_tmp_directory() {
+    echo "Verifying that the /tmp directory is writable"
+    test_temp_file=$(mktemp --tmpdir=/tmp)
+    if [ ! -e "${test_temp_file}" ]; then
+	echo "Unable to write to the /tmp directory"
+	exit "${ERR_TMP_NOT_WRITABLE}"
```
Comment (chmeyers) [inline containers/datalab/content/run.sh]: Just to double check, after the exit here the whole thing will be retried, right?

Comment (ojarjur) [inline containers/datalab/content/run.sh]: Yes, the kubelet (which is what launches the Docker container) will recreate the container.
