### PR TITLE
Fix Typescript errors TS2531 & TS2721

### LINKED ISSUE #1981: Typescript errors in local build
Hello,

I encountered the following typescript errors when trying to build Datalab locally. 

```
notebook.ts(176,5): error TS2531: Object is possibly 'null'.
test/settings-manager-test.ts(58,11): error TS2721: Cannot invoke an object which is possibly 'null'.
```

I used changes in the following branch to resolve the issue:
https://github.com/parthea/datalab/commit/282f1e3087f10ce2ebb2608bea7975845e8cac7b

### PR DESCRIPTION
**Pull request by parthea**
Fixes #1981

### CODE REVIEW

File: sources/web/datalab/polymer/test/settings-manager-test.ts [hunk 1]
```diff
@@ -55,7 +55,10 @@ describe('SettingsManager', () => {
               'script element should have the expected src');
           documentHeadCalled = true;
           const fakeEvent = document.createEvent("Event");
-          script.onload(fakeEvent); // Resolve our promise
+          if (script.onload)
```
Comment (yebrahim) [inline sources/web/datalab/polymer/test/settings-manager-test.ts]: nit: please move open brace to the same line as the condition.

**Comment by yebrahim** [comment]
Thanks @parthea.
